baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module.imports]
path = "github.com/future-wd/hugo-responsive-images"

[params.image]
renderHook = true

[markup.goldmark.renderer]
unsafe = true
